FIx build error by removing unused param (#1445)
Summary:
Pull Request resolved: https://github.com/pytorch/kineto/pull/1445

Fixing:

```
/pytorch/kineto/libkineto/test/RegisterLoggerFactoryTest.cpp: In lambda function:
/pytorch/kineto/libkineto/test/RegisterLoggerFactoryTest.cpp:182:64: error: unused parameter ‘path’ [-Werror=unused-parameter]
  182 |       "overwrite_warning_proto", [counter1](const std::string& path) {
      |                                             ~~~~~~~~~~~~~~~~~~~^~~~
/pytorch/kineto/libkineto/test/RegisterLoggerFactoryTest.cpp: In lambda function:
/pytorch/kineto/libkineto/test/RegisterLoggerFactoryTest.cpp:190:64: error: unused parameter ‘path’ [-Werror=unused-parameter]
  190 |       "overwrite_warning_proto", [counter2](const std::string& path) {
      |
```

Reviewed By: scotts

Differential Revision: D109585155

fbshipit-source-id: b1d06701d2975a8173940276b2d9802f1bfee74b