Use shared_timed_mutex instead of shared_mutex due to PyTorch using C++14. (#525)
Summary:
Pull Request resolved: https://github.com/pytorch/kineto/pull/525

std::shared_mutex is not available in C++14, and shows an error when incorporated into PyTorch CI. This patch replaces it with shared_timed_mutex, which is available, and is shared_mutex in GCC5.0.

To use std::shared_mutex, we must use C++17.

Test Plan:
Fixes this error:
```
/scratch/aaronshi/pytorch/third_party/kineto/libkineto/src/CuptiCallbackApi.cpp:21:31: error: ‘shared_mutex’ in namespace ‘std’ does not name a type
 using ReaderWriterLock = std::shared_mutex;
                               ^~~~~~~~~~~~
/scratch/aaronshi/pytorch/third_party/kineto/libkineto/src/CuptiCallbackApi.cpp:22:42: error: ‘ReaderWriterLock’ was not declared in this scope
 using ReaderLockGuard = std::shared_lock<ReaderWriterLock>;
                                          ^~~~~~~~~~~~~~~~
/scratch/aaronshi/pytorch/third_party/kineto/libkineto/src/CuptiCallbackApi.cpp:22:58: error: template argument 1 is invalid
 using ReaderLockGuard = std::shared_lock<ReaderWriterLock>;
                                                          ^
/scratch/aaronshi/pytorch/third_party/kineto/libkineto/src/CuptiCallbackApi.cpp:23:41: error: ‘ReaderWriterLock’ was not declared in this scope
 using WriteLockGuard = std::unique_lock<ReaderWriterLock>;
                                         ^~~~~~~~~~~~~~~~
/scratch/aaronshi/pytorch/third_party/kineto/libkineto/src/CuptiCallbackApi.cpp:23:57: error: template argument 1 is invalid
 using WriteLockGuard = std::unique_lock<ReaderWriterLock>;
                                                         ^
/scratch/aaronshi/pytorch/third_party/kineto/libkineto/src/CuptiCallbackApi.cpp:25:8: error: ‘ReaderWriterLock’ does not name a type
 static ReaderWriterLock callbackLock_;
        ^~~~~~~~~~~~~~~~
/scratch/aaronshi/pytorch/third_party/kineto/libkineto/src/CuptiCallbackApi.cpp: In member function ‘void libkineto::CuptiCallbackApi::__callback_switchboard(CUpti_CallbackDomain, CUpti_CallbackId, const CUpti_CallbackData*)’:
/scratch/aaronshi/pytorch/third_party/kineto/libkineto/src/CuptiCallbackApi.cpp:116:5: error: ‘ReaderLockGuard’ was not declared in this scope
     ReaderLockGuard rl(callbackLock_);
     ^~~~~~~~~~~~~~~
/scratch/aaronshi/pytorch/third_party/kineto/libkineto/src/CuptiCallbackApi.cpp: In member function ‘bool libkineto::CuptiCallbackApi::registerCallback(CUpti_CallbackDomain, libkineto::CuptiCallbackApi::CuptiCallBackID, libkineto::CuptiCallbackFn)’:
/scratch/aaronshi/pytorch/third_party/kineto/libkineto/src/CuptiCallbackApi.cpp:198:3: error: ‘WriteLockGuard’ was not declared in this scope
   WriteLockGuard wl(callbackLock_);
   ^~~~~~~~~~~~~~
/scratch/aaronshi/pytorch/third_party/kineto/libkineto/src/CuptiCallbackApi.cpp: In member function ‘bool libkineto::CuptiCallbackApi::deleteCallback(CUpti_CallbackDomain, libkineto::CuptiCallbackApi::CuptiCallBackID, libkineto::CuptiCallbackFn)’:
/scratch/aaronshi/pytorch/third_party/kineto/libkineto/src/CuptiCallbackApi.cpp:225:3: error: ‘WriteLockGuard’ was not declared in this scope
   WriteLockGuard wl(callbackLock_);
   ^~~~~~~~~~~~~~
```

Reviewed By: briancoutinho

Differential Revision: D34190117

Pulled By: aaronenyeshi

fbshipit-source-id: 3cd16060ac06639337088b5f5ef6251c58766358