FIx build error by removing unused param
Summary:
Fixing:

```
/pytorch/kineto/libkineto/test/RegisterLoggerFactoryTest.cpp: In lambda function:
/pytorch/kineto/libkineto/test/RegisterLoggerFactoryTest.cpp:182:64: error: unused parameter ‘path’ [-Werror=unused-parameter]
  182 |       "overwrite_warning_proto", [counter1](const std::string& path) {
      |                                             ~~~~~~~~~~~~~~~~~~~^~~~
/pytorch/kineto/libkineto/test/RegisterLoggerFactoryTest.cpp: In lambda function:
/pytorch/kineto/libkineto/test/RegisterLoggerFactoryTest.cpp:190:64: error: unused parameter ‘path’ [-Werror=unused-parameter]
  190 |       "overwrite_warning_proto", [counter2](const std::string& path) {
      |
```

Differential Revision: D109585155