Avoid macro expansion of ::max() on Windows (#535)
Summary:
Pull Request resolved: https://github.com/pytorch/kineto/pull/535

The usage of std::numeric_limits<T>::max() is failing on Windows due to windows.h defining max as a macro. To prevent the macro expansion, we need to use (std::numeric_limits<T)::max)(), which should still work for Linux.

Test Plan:
Fixes this error on Windows builds in PyTorch CI (win-vs2019-cpu-py3, win-vs2019-cuda11.3-py3):
```
2022-02-15T17:58:57.3638752Z C:\actions-runner\_work\pytorch\pytorch\third_party\kineto\libkineto\src\CuptiActivityProfiler.cpp(433): error C2589: '(': illegal token on right side of '::'
2022-02-15T17:58:57.3639989Z C:\actions-runner\_work\pytorch\pytorch\third_party\kineto\libkineto\src\CuptiActivityProfiler.cpp(433): error C2062: type 'unknown-type' unexpected
2022-02-15T17:58:57.3641170Z C:\actions-runner\_work\pytorch\pytorch\third_party\kineto\libkineto\src\CuptiActivityProfiler.cpp(433): error C2059: syntax error: ')'
```

Reviewed By: briancoutinho

Differential Revision: D34281765

Pulled By: aaronenyeshi

fbshipit-source-id: eac41cbcb4da5d73b70698c59bbb60bd2244cec0