fix: add libkineto missing public header (#837)
Summary:
To fix build error:
```
root@pc:~/libkineto/sample_programs# ./build.sh
In file included from kineto_playground.cpp:14:
/usr/local/include/kineto/libkineto.h:32:10: fatal error: LoggingAPI.h: No such file or directory
   32 | #include "LoggingAPI.h"
      |          ^~~~~~~~~~~~~~
compilation terminated
```

Pull Request resolved: https://github.com/pytorch/kineto/pull/837

Reviewed By: davidberard98

Differential Revision: D51592654

Pulled By: aaronenyeshi

fbshipit-source-id: 9d666c9efda28ce19ad28cd9674f074de1ed4fe5