Fixed use of designated initializers Windows (#976)
Summary:
Fix CUPTI code not compiling on MSVC due to designated initializers not working on Windows.
`C:\Work\pytorch\third_party\kineto\libkineto\src\CuptiActivityProfiler.cpp(658): error C7555: use of designated initializers requires at least '/std:c++20'`

Pull Request resolved: https://github.com/pytorch/kineto/pull/976

Reviewed By: aaronenyeshi

Differential Revision: D61810245

Pulled By: sraikund16

fbshipit-source-id: 240a8163477e70b3a3cef0a78bc7cea260d5528e