Ensures using valid Range Profiler headers with ifdefs (#533)
Summary:
Pull Request resolved: https://github.com/pytorch/kineto/pull/533

Guard the use of nvperf_host.h and cupti_profiler_target.h, which are only available cuda-10.1 and above (CUDA_VERSION >= 10010). Since CUPTIRangeProfiler based on NvPerfMetric, which is available cuda version > 10.00 and < 11.04, add that to ifdef too (#if defined(CUDART_VERSION) && CUDART_VERSION > 10000 && CUDART_VERSION < 11040).

Test Plan:
Fixes errors when these headers are not available:
```
/scratch/aaronshi/pytorch/third_party/kineto/libkineto/src/CuptiRangeProfilerApi.cpp:7:10: fatal error: nvperf_host.h: No such file or directory
 #include <nvperf_host.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
```

Reviewed By: briancoutinho

Differential Revision: D34190649

Pulled By: aaronenyeshi

fbshipit-source-id: 4990c97165eb4903392dae4c8cc37a407d669286