TB_Plugin_CI bug fix: add mpmath==1.3.0 to fix missing attribute rational
Summary:
mpmath released a new version 1.4.0 on Feb 23. This version causes TB CI to have an error: `AttributeError: module 'mpmath' has no attribute 'rational'`. To fix the CI issue, we need to downgrade to an older version of mpmath 1.3.0.

Fixes: https://github.com/pytorch/kineto/issues/878

Differential Revision: D54262113

Pulled By: aaronenyeshi