Fix missing #include <mutex> in RoctracerLogger.h (#898)
Summary:
Pull Request resolved: https://github.com/pytorch/kineto/pull/898

For ROCM builds in PyTorch, we need to include header <mutex> which defines the std::mutex used in RoctracerLogger.h.

Test Plan:
CI

This was the previous build error in [PyTorch CI for ciflow/rocm](https://hud.pytorch.org/failure?name=inductor%20%2F%20rocm6.0-py3.8-inductor%20%2F%20build&jobName=undefined&failureCaptures=%5B%22%2Fvar%2Flib%2Fjenkins%2Fworkspace%2Fthird_party%2Fkineto%2Flibkineto%2Fsrc%2FRoctracerLogger.h%3A223%3A8%3A%20error%3A%20%E2%80%98mutex%E2%80%99%20in%20namespace%20%E2%80%98std%E2%80%99%20does%20not%20name%20a%20type%22%5D):
```
2024-04-06T06:23:51.4288896Z In file included from /var/lib/jenkins/workspace/third_party/kineto/libkineto/src/RoctracerActivityApi.h:19,
2024-04-06T06:23:51.4291167Z                  from /var/lib/jenkins/workspace/third_party/kineto/libkineto/src/RoctracerActivityApi.cpp:9:
2024-04-06T06:23:51.4295136Z /var/lib/jenkins/workspace/third_party/kineto/libkineto/src/RoctracerLogger.h:223:8: error: ‘mutex’ in namespace ‘std’ does not name a type
2024-04-06T06:23:51.4297026Z   223 |   std::mutex rowsMutex_;
2024-04-06T06:23:51.4297677Z       |        ^~~~~
2024-04-06T06:23:51.4300019Z /var/lib/jenkins/workspace/third_party/kineto/libkineto/src/RoctracerLogger.h:25:1: note: ‘std::mutex’ is defined in header ‘<mutex>’; did you forget to ‘#include <mutex>’?
2024-04-06T06:23:51.4302589Z    24 | #include <roctracer_roctx.h>
2024-04-06T06:23:51.4303565Z   +++ |+#include <mutex>
2024-04-06T06:23:51.4304163Z    25 |
```

Reviewed By: davidberard98

Differential Revision: D55876676

Pulled By: aaronenyeshi

fbshipit-source-id: 5b77ceecf2a607e571c2d3aac8c8fdf1643a42fa